**DAY - 3**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name = 'ERPData')

In [ ]:
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
df.head(3)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27

In [ ]:
df.shape # quantity e.g. 50 rows and 3 columns

(50, 3)

In [ ]:
df.tail(3)

   MaterialID Location  Quantity
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
np.unique(df['MaterialID'])

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
np.unique(df.MaterialID) #another method to find unique

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
len(np.unique(df['MaterialID']))

6

In [ ]:
np.unique(df['Location'])

array(['MWH-1', 'MWH-2', 'MWH-3', 'MWH-4', 'MWH-5'], dtype=object)

In [ ]:
len(np.unique(df['Location']))

5

In [ ]:
df.columns.values # extract name of columns

array(['MaterialID', 'Location', 'Quantity'], dtype=object)

In [ ]:
df.columns.values[0] # access perticular column

'MaterialID'

In [ ]:
df.columns.values[0] = 'MatID' #change  column name
df.head(3)

     MatID Location  Quantity
0  TMI-43T    MWH-4        34
1  AXCP-78    MWH-1        67
2  LXCV-21    MWH-2        27

In [ ]:
df.columns.values[0] = 'MaterialID' #change  column name
df.head(3)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27

In [ ]:
ind = np.where(df.Quantity>=70) #to sort quantity >=70 using where

In [ ]:
len(ind[0]) #to find length of ind first column we will use [0]

15

In [ ]:
(df.Quantity>=70).sum() # second method to sort quantity >=70 using sum

np.int64(15)

In [ ]:
df1 = df.iloc[ind] #to assign df1
df1

   MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
12    TMI-43T    MWH-4        76
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
27    LXCV-21    MWH-5        83
33    TMI-43T    MWH-5       112
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [ ]:
ind = np.where((df.Quantity>=70) & (df.Location =='MWH-1'))
len(ind[0])

5

In [ ]:
df1 = df.iloc[ind]
df1

   MaterialID Location  Quantity
9     TMI-43T    MWH-1       120
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
48    AXCP-78    MWH-1        75

In [ ]:
ind = np.where((df.Quantity>=70) | (df.Location =='MWH-1')) # to check only one condition using OR | OPERATOR
len(ind[0])

21

In [ ]:
temp = df.iloc[np.where(df.Location=='MWH-2')] #to check total weight in location "MWH-2 "
sum(temp.Quantity)

397

In [ ]:
sum(df.iloc[np.where(df.Location=='MWH-2')].Quantity)

397

In [ ]:
(df.Quantity<50).sum()                     #VALUES LESS THAN 50 IN QUANTITY

np.int64(24)

In [ ]:
# to drop values less than 50
ind = np.where(df.Quantity<50)
df1 = df.drop(ind[0])
df1

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
17    SDRT-67    MWH-5       102
19    TMI-43T    MWH-4        52
21    TMI-43T    MWH-4        75
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
29    LXCV-21    MWH-5        57
31    TMI-43T    MWH-4        65
33    TMI-43T    MWH-5       112
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
41    SDRT-67    MWH-1        57
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
48    AXCP-78    MWH-1        75

In [ ]:
df1 = df.iloc[ind[0]].reset_index(drop=True)
df1

  MaterialID Location  Quantity
0    TMI-43T    MWH-1       120
1    AXCP-78    MWH-1       152
2    AXCP-78    MWH-1       109
3    AXCP-78    MWH-1       145
4    AXCP-78    MWH-1        75

In [ ]:
# add column Grade if Quantity values<=50 A, <100 B, <100 C
grd = []
for ctr in df.Quantity:
  if ctr<=50:
    grd.append('A')
  elif ctr<100:
    grd.append('B')
  else:
    grd.append('C')
df['Grade'] = grd

In [ ]:
df.head(15)

   MaterialID Location  Quantity Grade
0     TMI-43T    MWH-4        34     A
1     AXCP-78    MWH-1        67     B
2     LXCV-21    MWH-2        27     A
3     AXCP-78    MWH-5        65     B
4     AXCP-78    MWH-4        36     A
5     TMI-43T    MWH-4        78     B
6     TMI-43T    MWH-4        31     A
7     TMI-43T    MWH-2        29     A
8     GCVB-79    MWH-2        10     A
9     TMI-43T    MWH-1       120     C
10    SDRT-67    MWH-1        34     A
11    SDRT-67    MWH-4        58     B
12    TMI-43T    MWH-4        76     B
13    TMI-43T    MWH-4        32     A
14    TMI-43T    MWH-3        65     B

In [ ]:
df.Grade.value_counts() # to count number of occurnces of certain elements

Grade
A    24
B    20
C     6
Name: count, dtype: int64

# WAP OP OF WHICH THE NAME OF WAREHOUSE WHERE THE TOTAL QUANTITY IS HIGHEST  -->MWH-2 590

**DATA CLEAING-----------------------------------=================================**

1. handling null valures

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name = 'EmpInfo')
df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [ ]:
ind = np.where(df.Deptt.isnull())
ind

(array([3, 5]),)

In [ ]:
# split the table into 2 parts as no NAN and NAN only

In [ ]:
df1 = df.drop(ind[0]).reset_index(drop=True)
df1

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     SDRT-67    MWH-1        34
10    SDRT-67    MWH-4        58
11    TMI-43T    MWH-4        76
12    TMI-43T    MWH-4        32
13    TMI-43T    MWH-3        65
14    GCVB-79    MWH-2        87
15    SDRT-67    MWH-5        12
16    SDRT-67    MWH-5       102
17    TMI-43T    MWH-4        34
18    TMI-43T    MWH-4        52
19    TMI-43T    MWH-4        39
20    TMI-43T    MWH-4        75
21    DDBN-89    MWH-4        48
22    DDBN-89    MWH-5        71
23    DDBN-89    MWH-1        57
24    LXCV-21    MWH-5        83
25    LXCV-21    MWH-5        34
26    LXCV-21    MWH-5        57
27    DDBN-89    MWH-4        27
28    TMI-43T    MWH-4        65
29    TMI-43T    MWH-4        43
30    TMI-43T    MWH-5       112
31    GCVB-79    MWH-5        26
32    GCVB-79    MWH-2        31
33    GCVB-79    MWH-2        28
34    AXCP-78    MWH-5        65
35    AXCP-78    MWH-5        70
36    DDBN-89    MWH-1        34
37    SDRT-67    MWH-1        57
38    SDRT-67    MWH-2        31
39    DDBN-89    MWH-3        38
40    LXCV-21    MWH-3        42
41    DDBN-89    MWH-2        69
42    AXCP-78    MWH-2        85
43    AXCP-78    MWH-3        29
44    DDBN-89    MWH-1        39

In [ ]:
df2 = df.iloc[ind[0]].reset_index(drop=True) # to get what is dropped
df2

  MaterialID Location  Quantity
0    TMI-43T    MWH-1       120
1    AXCP-78    MWH-1       152
2    AXCP-78    MWH-1       109
3    AXCP-78    MWH-1       145
4    AXCP-78    MWH-1        75

In [ ]:
# to find where both empid and dept name is missing
df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [ ]:
df1 - df.drop(ind[0]) # to drop all nanvalues
ind = np.where((df.EmpID.isnull()) & df.Deptt.isnull())
ind

TypeError: unsupported operand type(s) for -: 'str' and 'str'

AFter getting datset for clean
identify missing value wala row
*   remoe that row
*  replace with something i.e. SOme other values
can be replaced by median



Another command After getting datset
to get snapshot of dataset
* df.info

In [ ]:
df.loc[ind[0], 'Deptt'] = 'Fresher' #replacing dept values with fresher
df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342  Fresher  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN  Fresher  ER534867
6   Deepak   NaN  Quality  RF453432

In [ ]:
# to find how many null ae there
df.EmpID.isnull().sum()

np.int64(2)

In [ ]:
# all rows having any single missing value will be dropped
temp = df.dropna().reset_index(drop=True)
temp

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2    Arjun  A342  Fresher  RF453432
3    Rishi  R475    Prodn  DF453278

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   EmpID     5 non-null      object
 2   Deptt     7 non-null      object
 3   Passport  7 non-null      object
dtypes: object(4)
memory usage: 356.0+ bytes

2. handling duplicate values

In [ ]:
ind = np.where(df.Passport.duplicated(keep=False)) # first repeated occurance was not prited when u use keep=false all duplicates are repeated
ind

(array([0, 2, 3, 4, 6]),)

3. Data Validation

Groupp By  Commands

In [ ]:
grp1 = df.groupby('Location') #Grouping has to be done based on location

In [ ]:
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [ ]:
grp1.get_group('MWH-2')

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85

In [ ]:
df1 = grp1.get_group('MWH-2').reset_index(drop=True)

In [ ]:
pd.concat([grp1.get_group('MWH-2'),grp1.get_group('MWH-3')])

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
14    TMI-43T    MWH-3        65
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29

In [ ]:
df2 = grp1.Quantity.agg(np.sum).reset_index()
df2

/tmp/ipykernel_21603/378047920.py:1: FutureWarning: The provided callable <function sum at 0x79b00c920860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df2 = grp1.Quantity.agg(np.sum).reset_index()

  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697

In [ ]:
df2 = grp1.Quantity.agg(np.mean).reset_index()
df2

/tmp/ipykernel_21603/3234420868.py:1: FutureWarning: The provided callable <function mean at 0x79b00c921940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df2 = grp1.Quantity.agg(np.mean).reset_index()

  Location   Quantity
0    MWH-1  80.818182
1    MWH-2  44.111111
2    MWH-3  43.500000
3    MWH-4  48.533333
4    MWH-5  63.363636

In [ ]:
df2 = grp1.Quantity.agg(np.size).reset_index()

In [ ]:
locn1 = ['Mumbai','Mumbai','Mumbai','Pune','Pune']
course = ['AI', 'ML', 'DS', 'AI', 'DS']
marks1 = [45,78,65,35,89]
marks2 = [80,76,59,82,49]

In [ ]:
mydf = pd.DataFrame({'Sudeep':marks1, 'Ruchika':marks2},index=[locn1,course])
mydf

           Sudeep  Ruchika
Mumbai AI      45       80
       ML      78       76
       DS      65       59
Pune   AI      35       82
       DS      89       49

In [ ]:
mydf.index.names = ['Location0','Subject']
mydf

                   Sudeep  Ruchika
Location0 Subject
Mumbai    AI           45       80
          ML           78       76
          DS           65       59
Pune      AI           35       82
          DS           89       49

In [ ]:
mydf.loc['Mumbai']

         Sudeep  Ruchika
Subject
AI           45       80
ML           78       76
DS           65       59

In [ ]:
mydf.xs('AI', level='Subject') #dataframe with multi index

           Sudeep  Ruchika
Location0
Mumbai         45       80
Pune           35       82

In [ ]:
grp1 = df.groupby('MaterialID')
grp1.groups
grp1.get_group('SDRT-67')

   MaterialID Location  Quantity
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31

In [ ]:
grp1.Quantity.agg(np.sum) #grouping can be done on categorical data

/tmp/ipykernel_2807/1212771957.py:1: FutureWarning: The provided callable <function sum at 0x7dc5f9520860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg(np.sum)

MaterialID
AXCP-78    898
DDBN-89    383
GCVB-79    182
LXCV-21    243
SDRT-67    294
TMI-43T    885
Name: Quantity, dtype: int64

In [ ]:
grp1 = df.groupby(['Location', 'MaterialID']) #location comes first it becomes primary index and material is is secondary index
grp1.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [ ]:
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
grp1.Quantity.agg('sum')

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [ ]:
grp1.agg([np.sum, np.mean, np.size])

/tmp/ipykernel_2807/2206296802.py:1: FutureWarning: The provided callable <function sum at 0x7dc5f9520860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.agg([np.sum, np.mean, np.size])
/tmp/ipykernel_2807/2206296802.py:1: FutureWarning: The provided callable <function mean at 0x7dc5f9521940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.agg([np.sum, np.mean, np.size])

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1
MWH-3    AXCP-78          29   29.000000    1
         DDBN-89          38   38.000000    1
         LXCV-21          42   42.000000    1
         TMI-43T          65   65.000000    1
MWH-4    AXCP-78          36   36.000000    1
         DDBN-89          75   37.500000    2
         SDRT-67          58   58.000000    1
         TMI-43T         559   50.818182   11
MWH-5    AXCP-78         200   66.666667    3
         DDBN-89          71   71.000000    1
         GCVB-79          26   26.000000    1
         LXCV-21         174   58.000000    3
         SDRT-67         114   57.000000    2
         TMI-43T         112  112.000000    1

In [ ]:
newdf = grp1.agg([np.sum, np.mean, np.size])
newdf.loc[['MWH-1','MWH-2']] #both are primary keys

/tmp/ipykernel_2807/1338026780.py:1: FutureWarning: The provided callable <function sum at 0x7dc5f9520860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  newdf = grp1.agg([np.sum, np.mean, np.size])
/tmp/ipykernel_2807/1338026780.py:1: FutureWarning: The provided callable <function mean at 0x7dc5f9521940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  newdf = grp1.agg([np.sum, np.mean, np.size])

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1

# **SORTING OF DF**

In [ ]:
df_sorted = df.sort_values('Quantity', ascending=False)
df_sorted.tail()

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27
34    GCVB-79    MWH-5        26
16    SDRT-67    MWH-5        12
8     GCVB-79    MWH-2        10

In [ ]:
df_sorted = df.sort_values(['MaterialID','Location', 'Quantity'])
df_sorted.head(6)

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152
46    AXCP-78    MWH-2        85

In [ ]:
df_sorted = df.sort_values(['MaterialID','Location', 'Quantity'], ascending=[True,False,True])
df_sorted.head(6)

   MaterialID Location  Quantity
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
4     AXCP-78    MWH-4        36
47    AXCP-78    MWH-3        29
46    AXCP-78    MWH-2        85

In [ ]:
pune = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name= 'Pune')
mumbai = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name = 'Mumbai')

In [ ]:
pune
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B
5     Vinod          AI     C

In [ ]:
pd.merge(pune,mumbai)

Empty DataFrame
Columns: [Name, Subject, Grade]
Index: []

In [ ]:
pd.merge(pune,mumbai, on='Subject') # merges 2 if they are haing same subject # common sunj in punne and mumbbai

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [ ]:
pd.merge(pune, mumbai, on= ['Subject','Grade'],how='inner') # inner finds common in both

    Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [ ]:
pd.merge(pune, mumbai, on= ['Subject','Grade'],how='outer') # outer finds all

    Name_x      Subject Grade    Name_y
0    Vinod           AI     B       NaN
1      NaN           AI     C     Vinod
2   Hitesh   CommSkills     A     Arjun
3      NaN     MLPython     B  Abhishek
4    Manoj     MLPython     C       NaN
5   Suyash  ProjectMgmt     B       NaN
6   Rakesh       Python     A    Chetan
7      NaN    Six Sigma     A   Vaibhav
8  Vaibhav   Statistics     B   Deepika

In [ ]:
pd.merge(pune, mumbai, on= ['Subject'],how='outer') # outer finds all subjects

    Name_x      Subject Grade_x    Name_y Grade_y
0    Vinod           AI       B     Vinod       C
1   Hitesh   CommSkills       A     Arjun       A
2    Manoj     MLPython       C  Abhishek       B
3   Suyash  ProjectMgmt       B       NaN     NaN
4   Rakesh       Python       A    Chetan       A
5      NaN    Six Sigma     NaN   Vaibhav       A
6  Vaibhav   Statistics       B   Deepika       B

In [ ]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [ ]:
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B
5     Vinod          AI     C

In [ ]:
pd.merge(pune, mumbai, on= ['Subject'],how='left') #in left columns which are exclusibevely in left side that wont be nan

    Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN
5    Vinod           AI       B     Vinod       C

                                                                    Day 5

In [ ]:
df.head(3) # from erp dataset

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27

In [ ]:
x1 = np.random.randint(10,80,50) # generating new values
df['Value'] = x1 # adding values to columns
df.head(5)

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     52
1    AXCP-78    MWH-1        67     70
2    LXCV-21    MWH-2        27     32
3    AXCP-78    MWH-5        65     42
4    AXCP-78    MWH-4        36     20

In [ ]:
#grouping will be always done on categorical data because grouping will only take specific values

In [ ]:
grp1 = df.groupby('MaterialID') #grouping done only on basis of material ID #keys of dict are arranged in alpha betically and unique keys all
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [ ]:
df.iloc[[1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48]]

   MaterialID Location  Quantity  Value
1     AXCP-78    MWH-1        67     70
3     AXCP-78    MWH-5        65     42
4     AXCP-78    MWH-4        36     20
24    AXCP-78    MWH-1       152     68
25    AXCP-78    MWH-1       109     79
37    AXCP-78    MWH-5        65     31
38    AXCP-78    MWH-5        70     18
39    AXCP-78    MWH-1       145     28
46    AXCP-78    MWH-2        85     46
47    AXCP-78    MWH-3        29     39
48    AXCP-78    MWH-1        75     69

In [ ]:
grp1.get_group('SDRT-67') #direct command

   MaterialID Location  Quantity  Value
10    SDRT-67    MWH-1        34     26
11    SDRT-67    MWH-4        58     57
16    SDRT-67    MWH-5        12     29
17    SDRT-67    MWH-5       102     74
41    SDRT-67    MWH-1        57     43
42    SDRT-67    MWH-2        31     28

In [ ]:
grp1.Quantity.mean() # or
# grp1.Quantity.agg(np.mean)

MaterialID
AXCP-78    81.636364
DDBN-89    47.875000
GCVB-79    36.400000
LXCV-21    48.600000
SDRT-67    49.000000
TMI-43T    59.000000
Name: Quantity, dtype: float64

In [ ]:
grp1.Quantity.agg([np.size, np.sum, np.mean])

/tmp/ipykernel_3232/2956438982.py:1: FutureWarning: The provided callable <function sum at 0x7c6aefd30860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1.Quantity.agg([np.size, np.sum, np.mean])
/tmp/ipykernel_3232/2956438982.py:1: FutureWarning: The provided callable <function mean at 0x7c6aefd31940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp1.Quantity.agg([np.size, np.sum, np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [ ]:
s1 = grp1.Quantity.agg(np.size)
d1  = pd.DataFrame(s1) # convert intto df

In [ ]:
d1.loc['SDRT-67']

Quantity    6
Name: SDRT-67, dtype: int64

In [ ]:
np.where(d1.index=='SDRT-67') # to extract value using label

(array([4]),)

In [ ]:
d1.iloc[np.where(d1.index=='SDRT-67')] # to extract value using index

            Quantity
MaterialID
SDRT-67            6

In [ ]:
d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])
d2

/tmp/ipykernel_3232/1435843678.py:1: FutureWarning: The provided callable <function sum at 0x7c6aefd30860> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])
/tmp/ipykernel_3232/1435843678.py:1: FutureWarning: The provided callable <function mean at 0x7c6aefd31940> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  d2 = grp1.Quantity.agg([np.size,np.sum,np.mean])

            size  sum       mean
MaterialID
AXCP-78       11  898  81.636364
DDBN-89        8  383  47.875000
GCVB-79        5  182  36.400000
LXCV-21        5  243  48.600000
SDRT-67        6  294  49.000000
TMI-43T       15  885  59.000000

In [ ]:
d2.loc['SDRT-67','sum']

np.int64(294)

In [ ]:
d2.iloc[4,1]

np.int64(294)

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/CDAC_DataBook.xlsx", sheet_name = 'Health')

In [ ]:
df

   Country       Disease  2019  2020  2021
0    India        Cancer    12    94    35
1       UK        Cancer    95    19    84
2       US        Cancer    98    19    53
3    Japan        Cancer    89    52    14
4    India         Covid    38    19    62
5       UK         Covid    69    73    35
6       US         Covid    87    97    35
7    Japan         Covid    14    12    90
8    India  Heart Attack    84    10    98
9       UK  Heart Attack    44    17    24
10      US  Heart Attack    34    40    54
11   Japan  Heart Attack    11    43    75

In [ ]:
df1 = df.melt(id_vars=['Country','Disease'], var_name='Year', value_name='Cases')
df1

   Country       Disease  Year  Cases
0    India        Cancer  2019     12
1       UK        Cancer  2019     95
2       US        Cancer  2019     98
3    Japan        Cancer  2019     89
4    India         Covid  2019     38
5       UK         Covid  2019     69
6       US         Covid  2019     87
7    Japan         Covid  2019     14
8    India  Heart Attack  2019     84
9       UK  Heart Attack  2019     44
10      US  Heart Attack  2019     34
11   Japan  Heart Attack  2019     11
12   India        Cancer  2020     94
13      UK        Cancer  2020     19
14      US        Cancer  2020     19
15   Japan        Cancer  2020     52
16   India         Covid  2020     19
17      UK         Covid  2020     73
18      US         Covid  2020     97
19   Japan         Covid  2020     12
20   India  Heart Attack  2020     10
21      UK  Heart Attack  2020     17
22      US  Heart Attack  2020     40
23   Japan  Heart Attack  2020     43
24   India        Cancer  2021     35
25      UK        Cancer  2021     84
26      US        Cancer  2021     53
27   Japan        Cancer  2021     14
28   India         Covid  2021     62
29      UK         Covid  2021     35
30      US         Covid  2021     35
31   Japan         Covid  2021     90
32   India  Heart Attack  2021     98
33      UK  Heart Attack  2021     24
34      US  Heart Attack  2021     54
35   Japan  Heart Attack  2021     75

In [ ]:
df.shape
df1.shape

(36, 4)

In [ ]:
df2 = df1.pivot_table(values='Cases', index=['Country', 'Year'],columns="Disease") #
df2

Disease       Cancer  Covid  Heart Attack
Country Year
India   2019    12.0   38.0          84.0
        2020    94.0   19.0          10.0
        2021    35.0   62.0          98.0
Japan   2019    89.0   14.0          11.0
        2020    52.0   12.0          43.0
        2021    14.0   90.0          75.0
UK      2019    95.0   69.0          44.0
        2020    19.0   73.0          17.0
        2021    84.0   35.0          24.0
US      2019    98.0   87.0          34.0
        2020    19.0   97.0          40.0
        2021    53.0   35.0          54.0

In [ ]:
df2 = df1.pivot_table(values='Cases', index=['Country', 'Year'],columns="Disease").reset_index()
df2.head( )

Disease Country  Year  Cancer  Covid  Heart Attack
0         India  2019    12.0   38.0          84.0
1         India  2020    94.0   19.0          10.0
2         India  2021    35.0   62.0          98.0
3         Japan  2019    89.0   14.0          11.0
4         Japan  2020    52.0   12.0          43.0

In [ ]:
# using erp dataset below
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
df1 = df.pivot_table(values='Quantity', index=['MaterialID'],columns='Location')
df1.head()

Location         MWH-1  MWH-2  MWH-3  MWH-4      MWH-5
MaterialID
AXCP-78     109.600000   85.0   29.0   36.0  66.666667
DDBN-89      43.333333   69.0   38.0   37.5  71.000000
GCVB-79            NaN   39.0    NaN    NaN  26.000000
LXCV-21            NaN   27.0   42.0    NaN  58.000000
SDRT-67      45.500000   31.0    NaN   58.0  57.000000

In [ ]:
df1 = df.pivot_table(values='Quantity', index=['MaterialID'],columns='Location',aggfunc='size')
df1

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78       5.0    1.0    1.0    1.0    3.0
DDBN-89       3.0    1.0    1.0    2.0    1.0
GCVB-79       NaN    4.0    NaN    NaN    1.0
LXCV-21       NaN    1.0    1.0    NaN    3.0
SDRT-67       2.0    1.0    NaN    1.0    2.0
TMI-43T       1.0    1.0    1.0   11.0    1.0