**Pandas**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x1 =  [4,8,4,3,2]
type(x1)

list

In [ ]:
s1 = pd.Series(x1)

In [ ]:
s1

0    4
1    8
2    4
3    3
4    2
dtype: int64

In [ ]:
s1 = pd.Series(x1, index = ['A','B','C','D','E'])
s1

A    4
B    8
C    4
D    3
E    2
dtype: int64

In [ ]:
s1.iloc[2]        #to get the index value use "iloc" i for index and loc is location

np.int64(4)

In [ ]:
s1.loc['C'] #to find values from label

np.int64(4)

In [ ]:
s2 = pd.Series([1,2,3,4,5],index = ['A','B','A','D','B'])
s2

A    1
B    2
A    3
D    4
B    5
dtype: int64

In [ ]:
s2.loc['A']

A    1
A    3
dtype: int64

In [ ]:
s2.iloc[2]

np.int64(3)

In [ ]:
s3 = pd.Series([3,9], index=['F','G'])
s3

F    3
G    9
dtype: int64

In [ ]:
s1 = pd.concat([s1,s3])
s1

A    4
B    8
C    4
D    3
E    2
F    3
G    9
dtype: int64

In [ ]:
len(s1)

7

In [ ]:
s1.iloc[4] = 9
s1

A    4
B    8
C    4
D    3
E    9
F    3
G    9
dtype: int64

In [ ]:
s1.loc['E'] = 11
s1

A     4
B     8
C     4
D     3
E    11
F     3
G     9
dtype: int64

In [ ]:
s2.loc['A'] = 19
s2

A    19
B     2
A    19
D     4
B     5
dtype: int64

In [ ]:
s1

A    4
B    8
C    4
D    3
F    3
G    9
dtype: int64

In [ ]:
s1 = s1.drop(['B']) # remove that label vlue
s1

A    4
C    4
D    3
F    3
G    9
dtype: int64

In [ ]:
s1.drop(s1.index[[3, 2]])
s1

A    4
C    4
D    3
F    3
G    9
dtype: int64

In [ ]:
s4 = pd.Series([2,3,2,2,4,4,3,4,4,4,4,5,5,2,4,5])

In [ ]:
s4.value_counts()

4    7
2    4
5    3
3    2
Name: count, dtype: int64

In [ ]:
s1.index[np.where(s1==9)[0]]

Index(['G'], dtype='object')

# **DATAFRAME**

In [ ]:
mydata = [['a', 10, 19000], ['b', 20, 20000],['c', 30, 30000], ['d', 40, 4000]]

In [ ]:
len(mydata)

4

In [ ]:
len(mydata[0])

3

In [ ]:
mydf = pd.DataFrame(mydata)
mydf

   0   1      2
0  a  10  19000
1  b  20  20000
2  c  30  30000
3  d  40   4000

In [ ]:
temp = pd.DataFrame(mydata, columns=['Name', 'ID', 'Balance'],
                       index=[1, 2, 3, 4])
temp

  Name  ID  Balance
1    a  10    19000
2    b  20    20000
3    c  30    30000
4    d  40     4000

In [ ]:
df1 = temp
df1

  Name  ID  Balance
1    a  10    19000
2    b  20    20000
3    c  30    30000
4    d  40     4000

In [ ]:
df1.iloc[1]

Name           b
ID            20
Balance    20000
Name: 2, dtype: object

In [ ]:
df1.loc[1]

Name           a
ID            10
Balance    19000
Name: 1, dtype: object

In [ ]:
df1 = mydf.iloc[[1,2]].reset_index(drop=True)
df1

   0   1      2
0  b  20  20000
1  c  30  30000

In [ ]:
df1 = mydf.iloc[[1,2]].reset_index()

In [ ]:
df1

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64

In [ ]:
stu_info = {'Name':['A','B','C','D'], 'RollNo':[1,2,3,4], 'Marks':[50,60,75,64]}

In [ ]:
df1 = pd.DataFrame(stu_info)
df1

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64

In [ ]:
newdf = pd.DataFrame([['E', 7, 80], ['F',  8, 90]],columns=df1.columns)
newdf

  Name  RollNo  Marks
0    E       7     80
1    F       8     90

In [ ]:
df2 = pd.concat([df1,newdf]).reset_index(drop=True)
df2

  Name  RollNo  Marks
0    A       1     50
1    B       2     60
2    C       3     75
3    D       4     64
4    E       7     80
5    F       8     90

In [ ]:
x1 = [67, 89,75,62,50,82]
df2['Marks 2'] = x1
df2

  Name  RollNo  Marks  Marks 2
0    A       1     50       67
1    B       2     60       89
2    C       3     75       75
3    D       4     64       62
4    E       7     80       50
5    F       8     90       82

In [ ]:
df2.at[3, 'Marks']=74
df2

  Name  RollNo  Marks  Marks 2
0    A       1     50       67
1    B       2     60       89
2    C       3     75       75
3    D       4     74       62
4    E       7     80       50
5    F       8     90       82

In [ ]:
df2.iat[1,3]

np.int64(89)

In [ ]:
mySubj = df2[['Name', 'Marks 2']]
mySubj

  Name  Marks 2
0    A       67
1    B       89
2    C       75
3    D       62
4    E       50
5    F       82

In [ ]:
df2.iloc[:,[1,2]]

   RollNo  Marks
0       1     50
1       2     60
2       3     75
3       4     74
4       7     80
5       8     90

In [ ]:
df2

  Name  RollNo  Marks  Marks 2
0    A       1     50       67
1    B       2     60       89
2    C       3     75       75
3    D       4     74       62
4    E       7     80       50
5    F       8     90       82

In [ ]:
df2.drop([1,4], axis=0)

  Name  RollNo  Marks  Marks 2
0    A       1     50       67
2    C       3     75       75
3    D       4     74       62
5    F       8     90       82

In [ ]:
df2.drop('RollNo', axis=1)

  Name  Marks  Marks 2
0    A     50       67
1    B     60       89
2    C     75       75
3    D     74       62
4    E     80       50
5    F     90       82

In [ ]:
df2.drop(['RollNo','Marks'], axis=1)

  Name  Marks 2
0    A       67
1    B       89
2    C       75
3    D       62
4    E       50
5    F       82